import type { SkillQuestion } from "@/features/assessment/types";

export const DEDUCTIVE_REASONING_QUESTIONS: SkillQuestion[] = [
  {
    key: "dr-q1",
    prompt: "Todos los mamíferos respiran aire.\nLos perros son mamíferos.",
    options: [
      { id: "a", text: "Todos los perros respiran aire" },
      { id: "b", text: "Algunos perros no respiran aire" },
      { id: "c", text: "Ningún perro respira aire" },
      { id: "d", text: "Ningún perro es mamífero" },
    ],
    correctOptionId: "a",
    points: 2,
    order: 1,
  },
  {
    key: "dr-q2",
    prompt: "Ningún pez camina.\nEl salmón es un pez.",
    options: [
      { id: "a", text: "El salmón no camina" },
      { id: "b", text: "Algunos peces caminan" },
      { id: "c", text: "El salmón camina" },
      { id: "d", text: "No se puede concluir" },
    ],
    correctOptionId: "a",
    points: 2,
    order: 2,
  },
  {
    key: "dr-q3",
    prompt: "Todos los balones son objetos.\nAlgunos objetos son rojos.",
    options: [
      { id: "a", text: "Algunos balones pueden ser rojos" },
      { id: "b", text: "Todos los balones son rojos" },
      { id: "c", text: "Algunos balones son rojos" },
      { id: "d", text: "Ningún balón es rojo" },
    ],
    correctOptionId: "a",
    points: 3,
    order: 3,
  },
  {
    key: "dr-q4",
    prompt: "Si leo, aprendo.\nSi aprendo, progreso.\nLeí.",
    options: [
      { id: "a", text: "Progreso" },
      { id: "b", text: "No progreso" },
      { id: "c", text: "No aprendí" },
      { id: "d", text: "Puede que progrese" },
    ],
    correctOptionId: "a",
    points: 3,
    order: 4,
  },
  {
    key: "dr-q5",
    prompt: "Si estudio matemáticas, mejoro lógica.\nNo mejoré lógica.",
    options: [
      { id: "a", text: "No estudié matemáticas" },
      { id: "b", text: "Estudié matemáticas" },
      { id: "c", text: "Puede que haya estudiado matemáticas" },
      { id: "d", text: "No se puede concluir" },
    ],
    correctOptionId: "a",
    points: 3,
    order: 5,
  },
  {
    key: "dr-q6",
    prompt: "Si estudio, apruebo.\nNo estudié.",
    options: [
      { id: "a", text: "Puede que haya aprobado" },
      { id: "b", text: "No aprobé" },
      { id: "c", text: "Aprobé" },
      { id: "d", text: "No me graduaré" },
    ],
    correctOptionId: "a",
    points: 3,
    order: 6,
  },
  {
    key: "dr-q7",
    prompt: "Si hay fuego, hay humo.\nHay humo.",
    options: [
      { id: "a", text: "Puede que haya fuego" },
      { id: "b", text: "Hay fuego" },
      { id: "c", text: "No hay fuego" },
      { id: "d", text: "El humo es negro" },
    ],
    correctOptionId: "a",
    points: 3,
    order: 7,
  },
  {
    key: "dr-q8",
    prompt: "Todos los científicos investigan.\nAlgunos investigadores enseñan.",
    options: [
      { id: "a", text: "No se puede concluir" },
      { id: "b", text: "Todos los científicos enseñan" },
      { id: "c", text: "Algunos científicos enseñan" },
      { id: "d", text: "Ningún científico enseña" },
    ],
    correctOptionId: "a",
    points: 4,
    order: 8,
  },
  {
    key: "dr-q9",
    prompt: "Todos los escritores leen.\nAlgunos lectores publican libros.\nAna es escritora.",
    options: [
      { id: "a", text: "Ana lee" },
      { id: "b", text: "Ana publica libros" },
      { id: "c", text: "Ana no publica libros" },
      { id: "d", text: "Todos los que leen escriben libros" },
    ],
    correctOptionId: "a",
    points: 4,
    order: 9,
  },
  {
    key: "dr-q10",
    prompt: "Si Laura trabaja, gana dinero.\nSi gana dinero, viaja.\nLaura no viajó.",
    options: [
      { id: "a", text: "Laura no trabajó" },
      { id: "b", text: "Laura trabajó" },
      { id: "c", text: "Laura está triste" },
      { id: "d", text: "No se puede concluir" },
    ],
    correctOptionId: "a",
    points: 4,
    order: 10,
  },
  {
    key: "dr-q11",
    prompt: "Algunos artistas son padres.\nTodos los padres son hombres.",
    options: [
      { id: "a", text: "Algunos artistas son hombres" },
      { id: "b", text: "Todos los artistas son hombres" },
      { id: "c", text: "Ningún artista es hombre" },
      { id: "d", text: "Todos los artistas pintan" },
    ],
    correctOptionId: "a",
    points: 4,
    order: 11,
  },
  {
    key: "dr-q12",
    prompt: "Ningún caballo vuela.\nAlgunos animales son caballos.",
    options: [
      { id: "a", text: "Algunos animales no vuelan" },
      { id: "b", text: "Todos los animales vuelan" },
      { id: "c", text: "Ningún animal es caballo" },
      { id: "d", text: "Algunos animales vuelan" },
    ],
    correctOptionId: "a",
    points: 4,
    order: 12,
  },
];
