import type { AttentionQuestion } from "@/features/assessment/types";

const IMG_BASE = "/assets/Atencion_Selectiva";

export const SELECTIVE_ATTENTION_QUESTIONS: AttentionQuestion[] = [
  {
    key: "sa-q1",
    gridRows: 3,
    gridCols: 3,
    distractorContent: { type: "text", value: "▲" },
    targetContent:     { type: "text", value: "▼" },
    points: 2,
    order: 1,
  },
  {
    key: "sa-q2",
    gridRows: 3,
    gridCols: 3,
    distractorContent: { type: "text", value: "p" },
    targetContent:     { type: "text", value: "q" },
    points: 2,
    order: 2,
  },
  {
    key: "sa-q3",
    gridRows: 4,
    gridCols: 4,
    distractorContent: { type: "text", value: "b" },
    targetContent:     { type: "text", value: "d" },
    points: 3,
    order: 3,
  },
  {
    key: "sa-q4",
    gridRows: 4,
    gridCols: 4,
    distractorContent: { type: "text", value: "→" },
    targetContent:     { type: "text", value: "←" },
    points: 3,
    order: 4,
  },
  {
    key: "sa-q5",
    gridRows: 4,
    gridCols: 4,
    distractorContent: { type: "text", value: "88" },
    targetContent:     { type: "text", value: "8B" },
    points: 3,
    order: 5,
  },
  {
    key: "sa-q6",
    gridRows: 5,
    gridCols: 5,
    distractorContent: { type: "text", value: "abc" },
    targetContent:     { type: "text", value: "abd" },
    points: 4,
    order: 6,
  },
  {
    key: "sa-q7",
    gridRows: 5,
    gridCols: 5,
    distractorContent: { type: "text", value: "▲▼▲" },
    targetContent:     { type: "text", value: "▲▲▲" },
    points: 4,
    order: 7,
  },
  {
    key: "sa-q8",
    gridRows: 5,
    gridCols: 5,
    distractorContent: { type: "image", src: `${IMG_BASE}/drill.png`,    alt: "taladro" },
    targetContent:     { type: "image", src: `${IMG_BASE}/drill_alt.png`, alt: "taladro diferente" },
    points: 4,
    order: 8,
  },
  {
    key: "sa-q9",
    gridRows: 5,
    gridCols: 5,
    distractorContent: { type: "text", value: "000", monoZero: true },
    targetContent:     { type: "text", value: "000", italic: true, monoZero: true },
    points: 4,
    order: 9,
  },
  {
    key: "sa-q10",
    gridRows: 5,
    gridCols: 5,
    distractorContent: { type: "text", value: "dad" },
    targetContent:     { type: "text", value: "bad" },
    points: 4,
    order: 10,
  },
  {
    key: "sa-q11",
    gridRows: 6,
    gridCols: 6,
    distractorContent: { type: "image", src: `${IMG_BASE}/scissors.png`,    alt: "tijeras" },
    targetContent:     { type: "image", src: `${IMG_BASE}/scissors_alt.png`, alt: "tijeras diferentes" },
    points: 5,
    order: 11,
  },
  {
    key: "sa-q12",
    gridRows: 6,
    gridCols: 6,
    distractorContent: { type: "text", value: "a1b2" },
    targetContent:     { type: "text", value: "a2b1" },
    points: 5,
    order: 12,
  },
  {
    key: "sa-q13",
    gridRows: 6,
    gridCols: 6,
    distractorContent: { type: "text", value: "pp" },
    targetContent:     { type: "text", value: "pq" },
    points: 5,
    order: 13,
  },
  {
    key: "sa-q14",
    gridRows: 6,
    gridCols: 6,
    distractorContent: { type: "image", src: `${IMG_BASE}/hammer.png`,    alt: "martillo" },
    targetContent:     { type: "image", src: `${IMG_BASE}/hammer_alt.png`, alt: "martillo diferente" },
    points: 5,
    order: 14,
  },
  {
    key: "sa-q15",
    gridRows: 7,
    gridCols: 7,
    distractorContent: { type: "text", value: "888" },
    targetContent:     { type: "text", value: "8B8" },
    points: 6,
    order: 15,
  },
  {
    key: "sa-q16",
    gridRows: 7,
    gridCols: 7,
    distractorContent: { type: "text", value: "↑↓↑" },
    targetContent:     { type: "text", value: "↑↑↑" },
    points: 6,
    order: 16,
  },
  {
    key: "sa-q17",
    gridRows: 7,
    gridCols: 7,
    distractorContent: { type: "image", src: `${IMG_BASE}/plug.png`,    alt: "enchufe" },
    targetContent:     { type: "image", src: `${IMG_BASE}/plug_alt.png`, alt: "enchufe diferente" },
    points: 6,
    order: 17,
  },
  {
    key: "sa-q18",
    gridRows: 7,
    gridCols: 7,
    distractorContent: { type: "text", value: "BOB" },
    targetContent:     { type: "text", value: "B0B", monoZero: true },
    points: 6,
    order: 18,
  },
];
