import type { AttentionQuestion } from "@/features/assessment/types";

export const SELECTIVE_ATTENTION_QUESTIONS: AttentionQuestion[] = [
  {
    key: "sa-q1",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 5,
    gridCols: 5,
    distractorChar: "b",
    targetChar: "d",
    targetIndex: 7,
    order: 1,
  },
  {
    key: "sa-q2",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 6,
    gridCols: 6,
    distractorChar: "p",
    targetChar: "q",
    targetIndex: 20,
    order: 2,
  },
  {
    key: "sa-q3",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 7,
    gridCols: 7,
    distractorChar: "d",
    targetChar: "b",
    targetIndex: 33,
    order: 3,
  },
  {
    key: "sa-q4",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 8,
    gridCols: 8,
    distractorChar: "n",
    targetChar: "m",
    targetIndex: 45,
    order: 4,
  },
  {
    key: "sa-q5",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 9,
    gridCols: 9,
    distractorChar: "q",
    targetChar: "p",
    targetIndex: 58,
    order: 5,
  },
  {
    key: "sa-q6",
    prompt: "Encuentra y pulsa el carácter diferente en la matriz.",
    gridRows: 10,
    gridCols: 10,
    distractorChar: "v",
    targetChar: "w",
    targetIndex: 73,
    order: 6,
  },
];
